config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :features, except: [:index, :show]
  end

  resource :user
  resources :user_sessions, only: [:create]
  get 'login', to: 'user_sessions#new', as: 'login'
  get 'logout', to: 'user_sessions#destroy', as: 'logout'

  root to: 'home#start'
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :project
  validates_presence_of :project
  scope :with_project, -> { includes(:project) }
  scope :estimated,    -> { where.not(max_days: nil, min_days: nil)}

  def avg_days
    (min_days + max_days) / 2.0
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :features

  scope :with_features, -> { includes(:features) }

  enum color: ['red', 'green', 'blue', 'cyan', 'teal']

  def expected_time
    features.inject(0.0) { |sum, el| sum + el.avg_days }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :require_user

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  def require_user
    return true if current_user
    flash[:error] = 'You must be logged in'
    redirect_to new_user_session_url
    false
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :set_project
  before_action :set_feature, only: [:show, :edit, :update, :destroy]

  # GET /features/1
  def show
  end

  # GET /features/new
  def new
    @feature = Feature.new
  end

  # GET /features/1/edit
  def edit
  end

  # POST /features
  # POST /features.json
  def create
    @feature = Feature.new(feature_params)
    @feature.project = @project

    respond_to do |format|
      if @feature.save
        format.html { redirect_to @project, notice: 'Feature was successfully created.' }
        format.json { render :show, status: :created, location: @feature }
      else
        format.html { render :new }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /features/1
  # PATCH/PUT /features/1.json
  def update
    respond_to do |format|
      if @feature.update(feature_params)
        format.html { redirect_to @project, notice: 'Feature was successfully updated.' }
        format.json { render :show, status: :ok, location: @feature }
      else
        format.html { render :edit }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature.destroy
    respond_to do |format|
      format.html { redirect_to features_url, notice: 'Feature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature
      @feature = Feature.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feature_params
      params.require(:feature).permit(:name, :project_id, :min_days, :max_days)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def start
    @settings     = SettingsPresenter.new(params[:settings_presenter] || {})
    @all_projects = Project.all
    @projects     = @settings.projects
    
    @manager      = Manager.new(@settings.developers, @settings.efficiency)
    @settings.features.each do |feature|
      @manager.distribute_feature(feature)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.with_features
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @features = @project.features
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :color)
    end
end

app/helpers/features_helper.rb
module FeaturesHelper
  def print_feature_block(feature, efficiency)
    content_tag :div, class: 'feature-block', style: "background: #{feature.project.color}; width: #{feature.avg_days*10/efficiency}px;" do
      feature.name      
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def print_dev_track(developer, start_date)
    content_tag :div, class: 'dev-track', style: "width: #{developer.width}px" do
      safe_join([print_time_line(developer, start_date)] + developer.features.map do |feature|
        print_feature_block(feature, developer.efficiency)
      end)
    end
  end

  def print_time_line(developer, start_date)
    content_tag :div, class: 'time-line' do
      safe_join([
        content_tag(:span, start_date, class: 'time-start'),
        content_tag(:span, start_date + (developer.expected_length).days, class: 'time-stop')
        ])
    end
  end
end

app/helpers/table_helper.rb
module TableHelper
  def generate_table(opts = {})
    TableBuilder.new(opts).generate
  end

  class TableBuilder
    include ActionView::Helpers::TagHelper
    include ActionView::Context
    def initialize(opts = {})
      @opts = opts
    end

    def generate
      content_tag :table, class: table_class do
        safe_join([
          table_header,
          table_body
        ])
      end
    end

    private

    def table_header
      return unless header = @opts[:header]
      content_tag :thead do
        table_row(true, header)
      end
    end

    def table_body
      return unless rows = @opts[:content]
      content_tag :tbody do
        safe_join(rows.map { |row| table_row(false, row) })
      end
    end

    def table_row(header, elements)
      return unless elements
      content_tag :tr do
        safe_join(elements.map { |e| table_cell(header, e) })
      end
    end

    def table_cell(header, element)
      tag_type = header ? :th : :td
      content_tag tag_type do
        element.to_s
      end
    end

    def table_class
      classes = ['table']
      classes << 'table-striped' if @opts[:striped]
      classes << 'js-datatable'  if @opts[:data_table]
      classes.join(' ')
    end
  end

end

app/views/features/_form.html.erb
<%= simple_form_for([@project, @feature]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :min_days %>
    <%= f.input :max_days %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/features/edit.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h1>Edit Feature</h1>

      <%= render 'form' %>

      <%= link_to 'Back', project_path(@project) %>
    </div>
  </section>
<% end %>

app/views/features/new.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h1><%= "New Feature in #{@project.name}" %></h1>

      <%= render 'form' %>

      <%= link_to 'Back', project_path(@project) %>
    </div>
  </section>
<% end %>

app/views/home/_settings_form.html.erb
<%= simple_form_for(@settings, url: request.path, method: :get) do |f| %>
  <div class="row">
    <div class="col-md-3">
      <%= f.input :developers %>
    </div>
    <div class="col-md-3">
      <%= f.input :parallell_projects %>
    </div>
    <div class="col-md-3">
      <%= f.input :start_date, input_html: { class: 'js-datepicker' } %>
    </div>
    <div class="col-md-3">
      <%= f.input :project_ids, collection: @all_projects.map { |p| [p.name, p.id] }, input_html: { multiple: true, class: 'js-chosen' } %>
    </div>


    <div class="col-md-3">
      <%= submit_tag 'Set', class: 'btn btn-default' %>
    </div>
  </div>
  
<% end %>

app/views/home/start.html.erb
<% content_for :content do %>
  <div class="container">
    <section>
      <h2>Settings</h2>
      <%= render 'home/settings_form' %>
    </section>
    <section>
      <h2>Time lines</h2>
      <% @manager.developers.each do |dev| %>
        <%= print_dev_track(dev, @settings.start_date) %>
      <% end %>
    </section>
    <section>
      <h2>Projects</h2>
      <% @projects.each do |project| %>
        <div>
          <span class="badge" style="background: <%= project.color %>;">
            <%= project.name %>
          </span>
        </div>
      <% end %>
    </section>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".first-navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%= image_tag "http://placehold.it/300x100&text=#{Rails.application.class.parent_name}", class: 'logo' %>
      <% end %>
    </div>

    <div class="navbar-collapse navbar-right first-navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Projects", projects_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= Rails.application.class.parent_name %></title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="page-wrap">
  <%= render "layouts/navbar" %>
  <%= yield :content %>
</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :color, collection: Project.colors.keys.zip(Project.colors.keys) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h1>Edit Project</h1>

      <%= render 'form' %>

      <%= link_to 'Back', projects_path %>
    </div>
  </section>
<% end %>

app/views/projects/index.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h1>Listing Projects - <%= link_to 'New Project', new_project_path, class: 'btn btn-primary btn-xs'%></h1>
      <%= generate_table(
        striped: true,
        data_table: true,
        header: [
          'Name', 'Color', 'Expected time', '', '', ''
          ],
        content: @projects.map do |project|
          [
            project.name,
            project.color,
            project.expected_time,
            link_to('Show', project_path(project)),
            link_to('Edit', edit_project_path(project)),
            link_to('Destroy', project, method: :delete, data: { confirm: 'Are you sure?' })
          ]
        end) %>
    </div>
  </section>
<% end %>

app/views/projects/new.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h1>New Project</h1>

      <%= render 'form' %>

      <%= link_to 'Back', projects_path %>
    </div>
  </section>
<% end %>

app/views/projects/show.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h1>
        <%= @project.name %>
      </h1>

      <h2>Listing Features - <%= link_to 'New Feature', new_project_feature_path(@project), class: 'btn btn-primary btn-xs'%></h2>
      <%= generate_table(
        striped: true,
        data_table: true,
        header: [
          'Name', 'Min days', 'Max days', '', ''
          ],
        content: @features.map do |feature|
          [
            feature.name,
            feature.min_days,
            feature.max_days,
            link_to('Edit', edit_project_feature_path(@project, feature)),
            link_to('Destroy', project_feature_path(@project, feature), method: :delete, data: { confirm: 'Are you sure?' })
          ]
        end) %>
      
      <%= link_to 'Back', projects_path, class: 'btn btn-primary' %>
      <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-primary' %>
    </div>
  </section>
<% end %>